### ISSUE TITLE
Routes deleted with latest update

### ISSUE THREAD

**Issue by starbuckviper** [Nnoggie/MythicDungeonTools#197]
Just updated to latest version 3.3.9 and went to check route, but no mobs are on any of the dungeons at all, the previous notes and arrows etc are there but no mobs or bosses at all. Have tried reloading and relogging completely but nothing fixed it as of yet. [https://imgur.com/a/y4AwjM3](url)

**Comment by blinkzz** [comment]
@starbuckviper, 
Nnoggie just went mad, and tries to break everything he has done so far on purpose
https://www.reddit.com/r/CompetitiveWoW/comments/kk9po9/method_dungeon_tools_map_data_may_be_getting

**Comment by WanderingFox** [comment]
1) Add-ons must be free of charge. All add-ons must be distributed free of charge. Developers may not create “premium” versions of add-ons with additional for-pay features, charge money to download an add-on, charge for services related to the add-on, or otherwise require some form of monetary compensation to download or access an add-on.
