### ISSUE TITLE
Latest update flagged by Windows Defender: Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by Payens** [Nnoggie/MythicDungeonTools#262]
The trojan in question is randomware. Why is it flagging it as such?

**Comment by Avabehe** [comment]
The same problem here, pls solve it

**Comment by nsc-jens** [comment]
Duplicate of #261

Can you run Windows update and install the latest Microsoft Defender Antivirus definitions and see of that solves the problem?

**Comment by marvellius** [comment]
@nsc-jens This worked perfectly for me and I had the same issue. Thank you very much for pointing that out.

**Comment by Nnoggie** [comment]
Windows Defender was causing problem of falsely flagging AddOn updates from curseforge as malware. This was an issue on Microsofts part with a faulty definition from Wednesday that has been since fixed. Downloading the newest definition will resolve the issue. Learn more here: https://www.microsoft.com/en-us/wdsi/defenderupdates
