### ISSUE TITLE
Latest release has an odd set of things stuck to cursor on initial login

### ISSUE THREAD

**Issue by TheCheat54** [Nnoggie/MythicDungeonTools#286]
With version 3.8.9 that was released yesterday, I am getting an odd anomaly stuck to my mouse cursor the first time I log in after launching the game. It clears itself if I reload UI or swap characters without exiting the game. See the below screenshot link.

https://imgur.com/a/xk6mj0m

**Comment by TheCheat54** [comment]
And to clarify, I verified this doesn't happen by disabling MDT before logging in after a fresh game launch. It is reproducible.

**Comment by Nnoggie** [comment]
Please specify your problem. What version of the game and AddOn are you using? When does the problem arise? Provide error logs if possible through BugGrabber/BugSack AddOns. If you were using a route imported from a 3rd party please provide a link to it. Also if possible provide your MythicDungeonTools.lua from C:\Program Files (x86)\World of Warcraft_retail_\WTF\Account<accountname>\SavedVariables

This problem seems to stem from another AddOn. Try the following.
1. Have only MDT enabled.
2. Log in and see if the issuehappens.
3. Enable one of your other AddOns and repeat Step 2.
4. Repeat Step 4. until you find the AddOn causing the issue

**Comment by TheCheat54** [comment]
Issue seems to have been resolved, presumably by an update in the last week to whatever addon may have been conflicting.
